module:
    revision: 1
    group: 'media'
    edit_template: '@module/media/edit.html.twig'
    form_template: '@module/media/form.html.twig'

    module_options:
        form_fields:
            media:
                type: 'mediaVersion'
                type_options:
                    show_thumbnail: true

            aligment_media:
                type: 'choice'
                type_options:
                    choices:
                        "media.form.aligment_media.values.left": 'justify-content-start'
                        "media.form.aligment_media.values.right": 'justify-content-end'
                        "media.form.aligment_media.values.center": 'justify-content-center'
