module:
    revision: 1
    group: 'basic'
    edit_template: '@module/code/edit.html.twig'
    form_template: '@module/code/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            language:
                type: 'choice'
                type_options:
                    choice_translation_domain: false
                    choices:
                        "(auto)" : ''
                        "accesslog" : 'accesslog'
                        "actionscript" : 'actionscript'
                        "ada" : 'ada'
                        "apache" : 'apache'
                        "applescript" : 'applescript'
                        "arcade" : 'arcade'
                        "arduino" : 'arduino'
                        "xml" : 'xml'
                        "asciidoc" : 'asciidoc'
                        "bash" : 'bash'
                        "basic" : 'basic'
                        "c" : 'c'
                        "clean" : 'clean'
                        "coffeescript" : 'coffeescript'
                        "cpp" : 'cpp'
                        "csharp" : 'csharp'
                        "css" : 'css'
                        "markdown" : 'markdown'
                        "dart" : 'dart'
                        "delphi" : 'delphi'
                        "diff" : 'diff'
                        "django" : 'django'
                        "dns" : 'dns'
                        "dockerfile" : 'dockerfile'
                        "dsconfig" : 'dsconfig'
                        "dust" : 'dust'
                        "ruby" : 'ruby'
                        "excel" : 'excel'
                        "go" : 'go'
                        "gradle" : 'gradle'
                        "graphql" : 'graphql'
                        "groovy" : 'groovy'
                        "handlebars" : 'handlebars'
                        "http" : 'http'
                        "ini" : 'ini'
                        "java" : 'java'
                        "javascript" : 'javascript'
                        "json" : 'json'
                        "kotlin" : 'kotlin'
                        "latex" : 'latex'
                        "ldif" : 'ldif'
                        "mathematica" : 'mathematica'
                        "matlab" : 'matlab'
                        "mercury" : 'mercury'
                        "perl" : 'perl'
                        "nginx" : 'nginx'
                        "node-repl" : 'node-repl'
                        "pgsql" : 'pgsql'
                        "php" : 'php'
                        "php-template" : 'php-template'
                        "plaintext" : 'plaintext'
                        "powershell" : 'powershell'
                        "processing" : 'processing'
                        "profile" : 'profile'
                        "prolog" : 'prolog'
                        "properties" : 'properties'
                        "puppet" : 'puppet'
                        "purebasic" : 'purebasic'
                        "python" : 'python'
                        "python-repl" : 'python-repl'
                        "r" : 'r'
                        "routeros" : 'routeros'
                        "scala" : 'scala'
                        "scheme" : 'scheme'
                        "scss" : 'scss'
                        "shell" : 'shell'
                        "sql" : 'sql'
                        "stylus" : 'stylus'
                        "swift" : 'swift'
                        "yaml" : 'yaml'
                        "twig" : 'twig'
                        "typescript" : 'typescript'
                        "vbscript" : 'vbscript'
                        "vbscript-html" : 'vbscript-html'
                        "verilog" : 'verilog'
                        "vim" : 'vim'

            code:
                type: 'textarea'
                type_options:
                    constraints: [ 'notBlank' ]
                    attr:
                        data-allow-tabs: true
