module:
    revision: 1
    group: 'basic'
    edit_template: '@module/code/edit.html.twig'
    form_template: '@module/code/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            code:
                type: 'textarea'
                type_options:
                    constraints: [ 'notBlank' ]
