module:
    revision: 1
    group: 'block'
    edit_template: '@module/button/edit.html.twig'
    form_template: '@module/button/form.html.twig'

    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'buttonId'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'buttonClass'


            button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'buttonText'

            button_link:
                type: 'route'
                type_options:
