module:
    revision: 4
    group: 'basic'
    edit_template: '@module/button/edit.html.twig'
    form_template: '@module/button/form.html.twig'

    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'buttonId'

            button_style:
                type: 'choice'
                type_options:
                    choices:
                        "button.form.button_style.values.primary": 'btn btn-primary'
                        "button.form.button_style.values.secondary": 'btn btn-secondary'
                        "button.form.button_style.values.success": 'btn btn-success'
                        "button.form.button_style.values.danger": 'btn btn-danger'
                        "button.form.button_style.values.link": 'btn btn-link'
                        "button.form.button_style.values.outline_primary": 'btn btn-outline-primary'
                        "button.form.button_style.values.outline_secondary": 'btn btn-outline-secondary'
                        "button.form.button_style.values.outline_success": 'btn btn-outline-success'
                        "button.form.button_style.values.outline_danger": 'btn btn-outline-danger'
                        "button.form.button_style.values.none": ''
                    attr:
                        data-edit-class-input: 'buttonClass'

            button_classes:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'buttonClass'

            button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'buttonText'

            button_link:
                type: 'link'
                type_options:
