module:
    revision: 1
    group: 'basic'
    edit_template: '@module/wysiwyg/edit.html.twig'
    form_template: '@module/wysiwyg/form.html.twig'
    render_template: '@module/wysiwyg/render.html.twig'
    module_options:
        label_format: 'modules.wysiwyg.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'codeContainerId'
            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'wysiwygClassDiv'
            content:
                type: 'html'
                type_options:
                    attr:
                        data-edit-content-input: 'content'
                        data-wysiwyg: ''
               
