module:
    revision: 1
    group: 'basic'
    edit_template: '@module/wysiwyg/edit.html.twig'
    form_template: '@module/wysiwyg/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'wysiwygId'
            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'wysiwygClass'
            content:
                type: 'html'
                type_options:
                    attr:
                        data-edit-content-input: 'content'
               
