module:
    revision: 1
    group: 'basic'
    edit_template: '@module/wysiwyg/edit.html.twig'
    form_template: '@module/wysiwyg/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            content:
                type: 'html'

