module:
    revision: 1
    edit_template: '@module/title/edit.html.twig'
    form_template: '@module/title/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-content-edit-id: 'moduleBlock'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-content-edit-class: 'moduleBlock'

            type:
                type: 'choice'
                type_options:
                    choices:
                        "title.form.type.values.h1": h1
                        "title.form.type.values.h2": h2
                        "title.form.type.values.h3": h3
                        "title.form.type.values.h4": h4
                        "title.form.type.values.h5": h5
                        "title.form.type.values.h6": h6

            title:
                type: 'translationText'
