module:
    revision: 2
    group: 'basic'
    edit_template: '@module/title/edit.html.twig'
    form_template: '@module/title/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            spacing:
                type: 'spacing'

            type:
                type: 'choice'
                type_options:
                    default_value: h1
                    choices:
                        "title.form.type.values.h1": h1
                        "title.form.type.values.h2": h2
                        "title.form.type.values.h3": h3
                        "title.form.type.values.h4": h4
                        "title.form.type.values.h5": h5
                        "title.form.type.values.h6": h6

            title:
                type: 'translatable'
                type_options:
                    type_options:
                        constraints: [ 'notBlank' ]
