module:
    revision: 1
    edit_template: '@module/title/edit.html.twig'
    form_template: '@module/title/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    required: false
                    attr:
                        data-content-edit-id: 'moduleBlock'

            class:
                type: 'class'
                type_options:
                    required: false
                    attr:
                        data-content-edit-class: 'moduleBlock'

            type:
                type: 'choice'
                type_options:
                    choices:
                        h1: h1
                        h2: h2
                        h3: h3
                        h4: h4
                        h5: h5
                        h6: h6

            title:
                type: 'translationText'
                type_options:
                    languages: '%kernel.enabled_locales%'
                    default_language: '%kernel.default_locale%'