module:
    revision: 1
    edit_template: '@module/hero/edit.html.twig'
    form_template: '@module/hero/form.html.twig'

    module_options:
        form_fields:
            background:
                type: 'translatableImage'
                type_options:
                    image_types: ['background']

            other:
                type: 'translatableImage'
                type_options:
                    image_types: ['content']

            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'heroIdDiv'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'heroClassDiv'

            bg_color:
                type: 'color'
                type_options:
                    attr:
                        data-edit-bgcolor-input: 'heroColorDiv'

            title_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'titleClass'

            title:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'title'

            description:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'description'

            primary_button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'primaryButtonText'

            primary_button_link:
                type: 'route'
                type_options:

            secondary_button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'secondaryButtonText'
