module:
    revision: 1
    group: 'basic'
    edit_template: '@module/wysiwyg_translatable/edit.html.twig'
    form_template: '@module/wysiwyg_translatable/form.html.twig'
    render_template: '@module/wysiwyg_translatable/render.html.twig'
    module_options:
        label_format: 'modules.wysiwyg_translatable.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'codeContainerId'
            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'wysiwygClassDiv'
            content:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            data-edit-content-input: 'content'
                            data-wysiwyg: ''

                
