module:
    revision: 1
    group: 'basic'
    edit_template: '@module/wysiwyg_translatable/edit.html.twig'
    form_template: '@module/wysiwyg_translatable/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            content:
                type: 'translatable'
                type_options:
                    type: 'html'

                
