module:
    revision: 4
    group: 'block'
    edit_template: '@module/two_columns/edit.html.twig'
    form_template: '@module/two_columns/form.html.twig'

    module_options:
        form_fields:
            module_image:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        attr:
                            data-media-preview-input: 'moduleImage'
                        media_attr:
                            class: 'img-fluid'

            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'twoColumnsIdDiv'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'twoColumnsClassDiv'

            bg_color:
                type: 'color'
                type_options:
                    attr:
                        data-edit-bgcolor-input: 'twoColumnsBgColorDiv'

            title_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'titleClass'

            title:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'title'

            title_type:
                type: 'choice'
                type_options:
                    default_value: h2
                    choices:
                        "title.form.type.values.h1": h1
                        "title.form.type.values.h2": h2
                        "title.form.type.values.h3": h3
                        "title.form.type.values.h4": h4
                        "title.form.type.values.h5": h5
                        "title.form.type.values.h6": h6
                    attr:
                        data-cms-module-title-type-field: ''

            description:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            data-edit-content-input: 'description'
                            data-wysiwyg: ''

            primary_button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'primaryButtonText'

            primary_button_link:
                type: 'symfonyRoute'
                type_options:

            image_position_text:
                type: 'choice'
                type_options:
                    choices:
                        "two_columns.form.image_position_text.values.left": flex-row
                        "two_columns.form.image_position_text.values.right": flex-row-reverse
                    attr:
                        data-edit-class-input: 'imagePositionClass'
