module:
    revision: 5
    group: 'block'
    edit_template: '@module/two_columns/edit.html.twig'
    form_template: '@module/two_columns/form.html.twig'

    module_options:
        form_fields:
            module_image:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        media_attr:
                            class: 'img-fluid'

            id:
                type: 'id'

            class:
                type: 'class'

            bg_color:
                type: 'color'

            title_class:
                type: 'class'

            title:
                type: 'translatable'

            title_type:
                type: 'choice'
                type_options:
                    default_value: h2
                    choices:
                        "title.form.type.values.h1": h1
                        "title.form.type.values.h2": h2
                        "title.form.type.values.h3": h3
                        "title.form.type.values.h4": h4
                        "title.form.type.values.h5": h5
                        "title.form.type.values.h6": h6

            description:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            data-wysiwyg: ''

            primary_button_text:
                type: 'translatable'
                
            primary_button_link:
                type: 'link'

            image_position_text:
                type: 'choice'
                type_options:
                    default_value: 'flex-row'
                    choices:
                        "two_columns.form.image_position_text.values.left": flex-row
                        "two_columns.form.image_position_text.values.right": flex-row-reverse
