module:
    revision: 1
    group: 'container'
    edit_template: '@module/carousel/edit.html.twig'
    form_template: '@module/carousel/form.html.twig'
    module_type: 'Softspring\CmsBundle\Form\Module\ContainerModuleType'
    module_options:
        module_collection_class: 'row'
        module_row_class: 'col-auto'
        allowed_modules: ~
        allowed_container_modules: []
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            bg_color:
                type: 'color'

            items_per_slide:
                type: 'choice'
                type_options:
                    choices:
                        "carousel.form.items_per_slide.values.one": 1
                        "carousel.form.items_per_slide.values.two": 2
                        "carousel.form.items_per_slide.values.three": 3
                        "carousel.form.items_per_slide.values.four": 4
                        "carousel.form.items_per_slide.values.five": 5
                        "carousel.form.items_per_slide.values.auto": 'auto'
                        
            infinite_loop:
                type: 'choice'
                type_options:
                    choices:
                        "carousel.form.infinite_loop.values.yes": 1
                        "carousel.form.infinite_loop.values.no": 0
                        
            auto_play:
                type: 'choice'
                type_options:
                    choices:
                        "carousel.form.auto_play.values.yes": 1
                        "carousel.form.auto_play.values.no": 0
                        
            navigation:
                type: 'choice'
                type_options:
                    choices:
                        "carousel.form.navigation.values.yes": 1
                        "carousel.form.navigation.values.no": 0

            pagination:
                type: 'choice'
                type_options:
                    choices:
                        "carousel.form.pagination.values.yes": 1
                        "carousel.form.pagination.values.no": 0
