module:
    revision: 1
    form_template: '@module/grid/form.html.twig'
    module_type: 'Softspring\CmsBundle\Form\Module\ContainerModuleType'
    module_options:
        module_collection_class: 'row'
        module_row_class: 'col'
        allowed_modules: ~
        allowed_container_modules: []