module:
    revision: 3
    group: 'block'
    edit_template: '@module/card/edit.html.twig'
    form_template: '@module/card/form.html.twig'

    module_options:
        form_fields:
            background:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        media_attr:
                            class: 'img-fluid'
                        attr:
                            data-media-preview-input: 'backgroundImage'

            media:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        media_attr:
                            class: 'img-fluid'
                        attr:
                            data-media-preview-input: 'media'

            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'cardIdDiv'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'cardClassDiv'

            bg_color:
                type: 'color'
                type_options:
                    attr:
                        data-edit-bgcolor-input: 'cardColorDiv'

            title_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'titleClass'

            title:
                type: 'translatable'
                type_options:
                    type: 'text'
                    type_options:
                        attr:
                            data-edit-content-input: 'title'

            description:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            data-edit-content-input: 'description'
                            data-wysiwyg: ''

            primary_button_text:
                type: 'translatable'
                type_options:
                    type: 'text'
                    type_options:
                        attr:
                            data-edit-content-input: 'primaryButtonText'

            primary_button_link:
                type: 'symfonyRoute'
                type_options:

            primary_button_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'primaryButtonClass'

            content_position:
                type: 'choice'
                type_options:
                    choices:
                        "card.form.content_position.values.left": text-start
                        "card.form.content_position.values.right": text-end
                        "card.form.content_position.values.center": text-center
                    attr:
                        data-edit-class-input: 'contentPositionClass'
