module:
    revision: 1
    group: 'block'
    edit_template: '@module/card/edit.html.twig'
    form_template: '@module/card/form.html.twig'

    module_options:
        form_fields:
            background:
                type: 'translatableImage'
                type_options:
                    media_attr:
                        class: 'img-fluid'
                    children_attr:
                        data-media-preview-input: 'backgroundImage'
                    media_types:
                        background:
                            picture: '_default'

            other:
                type: 'translatableImage'
                type_options:
                    media_attr:
                        class: 'img-fluid'
                    media_types:
                        content_png:
                            image: 'sm'
                        content_jpeg:
                            image: 'sm'
                        icon_png:
                            image: '_default'

            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'cardIdDiv'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'cardClassDiv'

            bg_color:
                type: 'color'
                type_options:
                    attr:
                        data-edit-bgcolor-input: 'cardColorDiv'

            title_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'titleClass'

            title:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'title'

            description:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            data-edit-content-input: 'description'
                            data-wysiwyg: ''

            primary_button_text:
                type: 'translatableText'
                type_options:
                    children_attr:
                        data-edit-content-input: 'primaryButtonText'

            primary_button_link:
                type: 'route'
                type_options:

            primary_button_class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'primaryButtonClass'

            content_position:
                type: 'choice'
                type_options:
                    choices:
                        "card.form.content_position.values.left": text-start
                        "card.form.content_position.values.right": text-end
                        "card.form.content_position.values.center": text-center
                    attr:
                        data-edit-class-input: 'contentPositionClass'
