module:
    revision: 5
    group: 'block'
    edit_template: '@module/card/edit.html.twig'
    form_template: '@module/card/form.html.twig'

    module_options:
        form_fields:
            background:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        media_attr:
                            class: 'img-fluid'

            media:
                type: 'translatable'
                type_options:
                    type: 'mediaVersion'
                    type_options:
                        media_attr:
                            class: 'img-fluid'

            id:
                type: 'id'

            class:
                type: 'class'

            bg_color:
                type: 'color'

            title_class:
                type: 'class'

            title:
                type: 'translatable'
                type_options:
                    type: 'text'

            title_type:
                type: 'choice'
                type_options:
                    default_value: h2
                    choices:
                        "title.form.type.values.h1": h1
                        "title.form.type.values.h2": h2
                        "title.form.type.values.h3": h3
                        "title.form.type.values.h4": h4
                        "title.form.type.values.h5": h5
                        "title.form.type.values.h6": h6

            description:
                type: 'translatable'
                type_options:
                    type: 'html'

            primary_button_text:
                type: 'translatable'
                type_options:
                    type: 'text'

            primary_button_link:
                type: 'link'

            primary_button_class:
                type: 'class'

            content_position:
                type: 'choice'
                type_options:
                    choices:
                        "card.form.content_position.values.left": text-start
                        "card.form.content_position.values.right": text-end
                        "card.form.content_position.values.center": text-center
