module:
    revision: 1
    group: 'basic'
    edit_template: '@module/paragraph/edit.html.twig'
    form_template: '@module/paragraph/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'paragraph'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'paragraph'

            paragraph:
                type: 'translatable'
                type_options:
                    type_options:
                        constraints: [ 'notBlank' ]
                        attr:
                            data-edit-content-input: 'paragraph'
