module:
    revision: 1
    group: 'basic'
    edit_template: '@module/paragraph/edit.html.twig'
    form_template: '@module/paragraph/form.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            paragraph:
                type: 'translatable'
                type_options:
                    type: 'textarea'
                    type_options:
                        constraints: [ 'notBlank' ]
